# Generated by Django 5.0.2 on 2026-08-09 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coa", "0002_seed_account_types"),
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "cogs_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cogs_categories",
                        to="coa.account",
                    ),
                ),
                (
                    "inventory_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_categories",
                        to="coa.account",
                    ),
                ),
                (
                    "revenue_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_categories",
                        to="coa.account",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "product categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("stocked", "Stocked product"),
                            ("service", "Service"),
                        ],
                        default="stocked",
                        max_length=16,
                    ),
                ),
                (
                    "procurement_type",
                    models.CharField(
                        choices=[("buy", "Buy"), ("make", "Make")],
                        default="buy",
                        max_length=8,
                    ),
                ),
                (
                    "standard_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "sales_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("lead_time_days", models.PositiveIntegerField(default=0)),
                (
                    "safety_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "min_order_qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "order_multiple",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplied_products",
                        to="partners.businesspartner",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.productcategory",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.unitofmeasure",
                    ),
                ),
            ],
            options={
                "ordering": ["sku"],
                "indexes": [
                    models.Index(
                        fields=["procurement_type"],
                        name="products_pr_procure_1b64ed_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="products_pr_is_acti_ca4d9a_idx"
                    ),
                ],
            },
        ),
    ]
