# Generated by Django 5.0.2 on 2026-08-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="source_reference",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
