# Generated by Django 5.0.2 on 2026-08-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prefix", models.CharField(max_length=10, unique=True)),
                ("next_value", models.PositiveIntegerField(default=1)),
                ("padding", models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
