# Generated by Django 5.0.2 on 2026-08-09 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coa", "0002_seed_account_types"),
        ("invoices", "0002_invoice_journal_entry"),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="partners.businesspartner",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="revenue_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revenue_invoices",
                to="coa.account",
            ),
        ),
    ]
