# Generated by Django 5.0.2 on 2026-08-09 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mrp", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planned_orders",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="plannedorder",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planned_orders",
                to="mrp.mrprun",
            ),
        ),
        migrations.AddIndex(
            model_name="plannedorder",
            index=models.Index(fields=["status"], name="mrp_planned_status_770716_idx"),
        ),
        migrations.AddIndex(
            model_name="plannedorder",
            index=models.Index(
                fields=["order_type"], name="mrp_planned_order_t_e2bb23_idx"
            ),
        ),
    ]
