# Generated by Django 5.0.2 on 2026-08-09 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
        ("journal", "0002_journalentry_source_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="journal.journalentry",
            ),
        ),
    ]
