# Generated by Django 5.0.2 on 2026-08-09 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coa", "0002_seed_account_types"),
        ("invoices", "0003_invoice_partner_invoice_revenue_account"),
        ("journal", "0002_journalentry_source_reference"),
        ("products", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="sales.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_lines",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="deposit_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposit_payments",
                to="coa.account",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="journal.journalentry",
            ),
        ),
    ]
