# Generated by Django 5.0.2 on 2026-08-09 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stocklevel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_levels",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_moves",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_moves",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="stocklevel",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_levels",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmove",
            index=models.Index(
                fields=["product", "warehouse", "status"],
                name="inventory_s_product_80dc3f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmove",
            index=models.Index(
                fields=["move_type"], name="inventory_s_move_ty_0fa310_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmove",
            index=models.Index(
                fields=["move_date"], name="inventory_s_move_da_55029b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklevel",
            constraint=models.UniqueConstraint(
                fields=("product", "warehouse"), name="unique_stock_level"
            ),
        ),
    ]
