# Generated by Django 5.0.2 on 2026-08-09 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("manufacturing", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billofmaterials",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boms",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="bomline",
            name="bom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="manufacturing.billofmaterials",
            ),
        ),
        migrations.AddField(
            model_name="bomline",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="used_in_bom_lines",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="bom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_orders",
                to="manufacturing.billofmaterials",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_orders",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_orders",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddConstraint(
            model_name="billofmaterials",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("product",),
                name="one_active_bom_per_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="bomline",
            constraint=models.UniqueConstraint(
                fields=("bom", "component"), name="unique_component_per_bom"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["status"], name="manufacturi_status_305de3_idx"),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["due_date"], name="manufacturi_due_dat_9c4721_idx"
            ),
        ),
    ]
